// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {features} from '../models';
import {installer} from '../models';
import {db} from '../models';

export function AddRecentDirectory(arg1:string):Promise<void>;

export function CheckPatchCompatibility(arg1:string,arg2:Array<string>):Promise<main.CompatResult>;

export function CheckTargetDirectory(arg1:string):Promise<string>;

export function ForgetProject(arg1:number):Promise<void>;

export function GetComposerVersion():Promise<string>;

export function GetConfig():Promise<config.AppConfig>;

export function GetFeatureRegistry():Promise<features.Registry>;

export function GetFeatures():Promise<Array<features.Feature>>;

export function GetFluxLicenseKey():Promise<string>;

export function GetFluxUsername():Promise<string>;

export function GetGitVersion():Promise<string>;

export function GetHerdVersion():Promise<string>;

export function GetPHPVersion():Promise<string>;

export function GetRecentDirectories():Promise<Array<string>>;

export function GetStartupContext():Promise<main.StartupContext>;

export function GetStartupResult():Promise<main.StartupResult>;

export function HerdUnlink(arg1:string):Promise<void>;

export function Install(arg1:installer.InstallRequest):Promise<void>;

export function IsDebug():Promise<boolean>;

export function ListProjects():Promise<Array<db.Installation>>;

export function OpenFileInEditor(arg1:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function ResolveToken(arg1:string,arg2:Array<string>):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SetFluxLicenseKey(arg1:string):Promise<void>;

export function SetFluxUsername(arg1:string):Promise<void>;

export function SetRepository(arg1:string):Promise<void>;

export function WriteAuthJSON(arg1:string):Promise<void>;
