// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentDirectory(arg1) {
  return window['go']['main']['App']['AddRecentDirectory'](arg1);
}

export function CheckPatchCompatibility(arg1, arg2) {
  return window['go']['main']['App']['CheckPatchCompatibility'](arg1, arg2);
}

export function CheckTargetDirectory(arg1) {
  return window['go']['main']['App']['CheckTargetDirectory'](arg1);
}

export function ForgetProject(arg1) {
  return window['go']['main']['App']['ForgetProject'](arg1);
}

export function GetComposerVersion() {
  return window['go']['main']['App']['GetComposerVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFeatureRegistry() {
  return window['go']['main']['App']['GetFeatureRegistry']();
}

export function GetFeatures() {
  return window['go']['main']['App']['GetFeatures']();
}

export function GetFluxLicenseKey() {
  return window['go']['main']['App']['GetFluxLicenseKey']();
}

export function GetFluxUsername() {
  return window['go']['main']['App']['GetFluxUsername']();
}

export function GetGitVersion() {
  return window['go']['main']['App']['GetGitVersion']();
}

export function GetHerdVersion() {
  return window['go']['main']['App']['GetHerdVersion']();
}

export function GetPHPVersion() {
  return window['go']['main']['App']['GetPHPVersion']();
}

export function GetRecentDirectories() {
  return window['go']['main']['App']['GetRecentDirectories']();
}

export function GetStartupContext() {
  return window['go']['main']['App']['GetStartupContext']();
}

export function GetStartupResult() {
  return window['go']['main']['App']['GetStartupResult']();
}

export function HerdUnlink(arg1) {
  return window['go']['main']['App']['HerdUnlink'](arg1);
}

export function Install(arg1) {
  return window['go']['main']['App']['Install'](arg1);
}

export function IsDebug() {
  return window['go']['main']['App']['IsDebug']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenFileInEditor(arg1) {
  return window['go']['main']['App']['OpenFileInEditor'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ResolveToken(arg1, arg2) {
  return window['go']['main']['App']['ResolveToken'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetFluxLicenseKey(arg1) {
  return window['go']['main']['App']['SetFluxLicenseKey'](arg1);
}

export function SetFluxUsername(arg1) {
  return window['go']['main']['App']['SetFluxUsername'](arg1);
}

export function SetRepository(arg1) {
  return window['go']['main']['App']['SetRepository'](arg1);
}

export function WriteAuthJSON(arg1) {
  return window['go']['main']['App']['WriteAuthJSON'](arg1);
}
